### ISSUE TITLE
Cannot open extension after updating the new version

### ISSUE THREAD

**Issue by szehang** [paneron/extension-kit#4]
Hi @strogonoff, this is HSU student who is working with ISO-19160 project.

We got a problem at opening the extension kit after Paneron has been updated to alpha18. The problem is as follow:

<img width="486" alt="Screenshot 2021-01-19 at 9 36 08 PM" src="https://user-images.githubusercontent.com/49029044/105041826-72a9df00-5a9e-11eb-8a73-2e1a1a3c2d6d.png">

`21:32:56.728 › Repository view: Not provided by plugin @riboseinc/paneron-extension-s177228-extension 1.0.0-alpha6`

`21:32:56.728 › Repository view: Error requiring plugin /Users/harrylam/Library/Application Support/Electron/working_copies/45678 @riboseinc/paneron-extension-s177228-extension 1.0.0-alpha6 Error: Error requesting repository view from Paneron extension
      at getRepoInfo (webpack-internal:///./src/renderer/repositories/Details.tsx:282:19)`

**Comment by strogonoff** [comment]
Could you link to the repository with the version of extension code that results in that error?

**Comment by szehang** [comment]
This error occurs in both extension kit template-basic and template-registry. We just clone the extension kit and build it, we didn't change anything about the View.

**Comment by s177228** [comment]
Hi @strogonoff, I come from the same team with @szehang, the problem we found is when we following your instruction to test the extension locally(on paneron v1.0.0-alpha18), the template-basic and template-registry are not working like the image shown by @szehang , however, if I do in the same way to test another template(the template I cloned on November),it just works fine.

here is the source code: https://github.com/s177228/s177228-extension

**Comment by strogonoff** [comment]
I think this will be resolved with the beta release…￼
