### ISSUE TITLE
cannot install extension on paneron alpha 18

### ISSUE THREAD

**Issue by beebeebeeebeee** [paneron/extension-kit#6]
Hi @strogonoff, I am HSU student who is working on address profile project.

We are faced a problem that when we trying to build an extension from the latest version of **paneron/extension-template-registry** using **Paneron v1 (alpha18)**. 
By this command `env PANERON_DEV_PLUGIN=template-registry_ yarn dev`, and this extension is placed on `/Users/beemak/Library/Application Support/Electron/plugins/@riboseinc/paneron-extension-template-registry_`
The paneron will notify that `@riboseinc/paneron-extension-template-registry_ not installed` error.

![螢幕截圖 2021-01-23 下午6 06 31](https://user-images.githubusercontent.com/31685213/105575318-bbff7480-5da5-11eb-84de-bdf39adf04f4.png)

The terminal response:
```18:19:58.910 › Plugins: Worker event: {
    type: 'message',
    data: {
      type: 'error',
      uid: 14,
      error: {
        __error_marker: '$$error',
        message: "Failed to get package '@riboseinc/paneron-extension-template-registry_' Response error 404 Not Found",
        name: 'Error',
        stack: "Error: Failed to get package '@riboseinc/paneron-extension-template-registry_' Response error 404 Not Found\n" +
          '    at Object.eval (webpack-internal:///./node_modules/live-plugin-manager/dist/src/httpUtils.js:55:19)\n' +
          '    at Generator.next (<anonymous>)\n' +
          '    at fulfilled (webpack-internal:///./node_modules/live-plugin-manager/dist/src/httpUtils.js:5:58)\n' +
          '    at processTicksAndRejections (internal/process/task_queues.js:97:5)'
      }
    }
  }
```

Even we have tried to use the default provided extension e.g. **paneron-extension-geodetic-registry**, it will still notify that `@riboseinc/paneron-extension-geodetic-registry not installed` error.

![螢幕截圖 2021-01-23 下午6 11 07](https://user-images.githubusercontent.com/31685213/105575398-611a4d00-5da6-11eb-95f7-84897725169b.png)

However, when we try to run paneron with this command `yarn dev`.
The default provided extension e.g. **paneron-extension-geodetic-registry** will launch successfully.

![螢幕截圖 2021-01-23 下午6 19 07](https://user-images.githubusercontent.com/31685213/105575560-7e035000-5da7-11eb-821b-f86de030a5be.png)

**Comment by ronaldtse** [comment]
Thanks @beebeebeeebeee for the report. @strogonoff could you help? This would be a good chance to update the developer docs too.

**Comment by beebeebeeebeee** [comment]
Sorry, We have misunderstood the step and sloved the problem now. We found that the package.json name columns should be same with the extension folder name. And the extension works fine now.
